// Import the Metadata type from Next.js for defining page metadata
import type { Metadata } from "next";
// Import Google Fonts through Next.js optimized font loader
import { Geist, Geist_Mono } from "next/font/google"; // Using Geist/Geist_Mono fonts
// Import global CSS styles
import "./globals.css";
// Import the AppShell component which likely wraps the pages with the Sidebar/Layout
import AppShell from "@/components/AppShell";

// Configure the Geist Sans font
const geistSans = Geist({
  variable: "--font-geist-sans", // Define a CSS variable for this font
  subsets: ["latin"], // Load the latin character subset
});

// Configure the Geist Mono font (for code or technical data)
const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // Define a CSS variable for this font
  subsets: ["latin"], // Load the latin character subset
});

// Define global metadata for the application (Title, Description, etc.)
export const metadata: Metadata = {
  title: "Create Next App", // Title that appears in the browser tab
  description: "Generated by create next app", // Meta description for SEO
};

// The Root Layout component.
// This wraps ALL pages in the application.
export default function RootLayout({
  children, // The page content to be rendered inside the layout
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // define the html tag with language attribute
    <html lang="en">
      {/* Body tag with font classes applied */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* AppShell provides the main structural layout (Sidebar + Content Area) */}
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
